apiVersion: apps/v1
kind: Deployment
metadata:
  name: meido-webapp
  namespace: meido
spec:
  replicas: 2
  selector:
    matchLabels:
      app: meido-webapp
  template:
    metadata:
      labels:
        app: meido-webapp
    spec:
      containers:
        - name: meido-webapp
          image: <FRONTIMAGE>
          resources:
            requests:
              cpu: 70m
              memory: 64Mi
            limits:
              cpu: 128m
              memory: 128Mi
          ports:
            - containerPort: 3000
