apiVersion: apps/v1
kind: Deployment
metadata:
  name: meido
  namespace: meido
spec:
  selector:
    matchLabels:
      app: meido
  replicas: 3
  template:
    metadata:
      labels:
        app: meido
    spec:
      containers:
        - name: meido
          image: <BACKIMAGE>
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              cpu: "250m"
              memory: "64Mi"
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_PATH
              value: "redis:6379"
            - name: "PORT"
              value: "8080"
