apiVersion: apps/v1
kind: Deployment
metadata:
  name: meido-chat
  namespace: meido
spec:
  replicas: 2
  selector:
    matchLabels:
      app: meido-chat
  template:
    metadata:
      labels:
        app: meido-chat
    spec:
      containers:
        - name: meido-chat
          image: <FRONTIMAGE>
          resources:
            requests:
              cpu: 200m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          ports:
            - containerPort: 80
