name: CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build image
      env:
        SHA: ${{ github.sha }}
        FLASK_URL: ${{secrets.flask_url}}
      run: |
        echo $SHA
        docker build ./meido-api --tag notchman/meido-app:$SHA --build-arg flask_url=$FLASK_URL
        docker build ./flask --tag notchman/meido-flask:$SHA
    - name: docker login
      env:
        DOCKERHUB_USER: ${{ secrets.dockerhub_user }}
        DOCKERHUB_PASS: ${{ secrets.dockerhub_password }}
      run: docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
    - name: push image
      env:
        SHA: ${{ github.sha }}
      run: |
        docker push notchman/meido-app:$SHA
        docker push notchman/meido-flask:$SHA

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@master
    - name: deploy image
      env:
        GCP_KEY: ${{ secrets.gcp_key }}
        SHA: ${{ github.sha }}
      run: |
        echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" > google-cloud-sdk.list
        sudo cp google-cloud-sdk.list /etc/apt/sources.list.d
        curl https://packages.cloud.google.com/apt/doc/apt-key.gpg > apt-key.gpg
        sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add apt-key.gpg
        sudo apt-get update
        sudo apt-get install google-cloud-sdk kubectl
        echo $GCP_KEY > gcp_key.json
        gcloud auth activate-service-account --project=sapient-depot-302603 --key-file=gcp_key.json
        gcloud container clusters get-credentials meido --zone us-west1-a
        echo $SHA
        sed -i -e "s/<BACKIMAGE>/notchman\/meido-app:$SHA/" ./yamls/meido/deploy.yaml
        sed -i -e "s/<FLASKIMAGE>/notchman\/meido-flask:$SHA/" ./yamls/flask/deploy.yaml
        kubectl delete -f ./yamls/redis/deployment.yaml
        kubectl apply -f ./yamls/redis/deployment.yaml
        kubectl apply -f ./yamls/meido/deploy.yaml
        kubectl apply -f ./yamls/flask/deploy.yaml
        kubectl apply -f ./yamls/ingress.yaml
        kubectl get pods -o yaml
